# Generated by Django 4.1 on 2024-09-05 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='last_submission_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
